# Numpy Basics

Numpy, short for Numerical Python, is the fundamental package required for high performance scientific computing and data analysis.

While numpy by itslef does not provide very much high-level data anlaytical funcionality, having an understanding of NumPy arrays and array-oriented computing will help you use tools like pandas much more effectively.
While NumPy provides the computational foundation for these operations, you will likely want to use pandas as your basis for most kids of data analysis as it provides a rich, high-level interface making most common data tasks very concise and simple.

## The Numpy ndarray: A Multidimensional Array Object

One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large data sets in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements

An ndarray is a generic multidimensional container for homogeneous data; that is, <mark>all of the elements must be the same type. Every array has a *shape*, a tuple indicating the size of each dimension, and a *dtype*, an object describing the **data type** of the array.</mark>

The easiest way to create an array is to use the `array` function. This accepts any sequence-like object and produces a new NumPy array containing the passed data.

In [1]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array:

In [9]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

`np.array` tries to infer a good data type for the array that it creates. The data type is stored in a special *dtype* object.

In [12]:
arr1.dtype

dtype('float64')

There are a number of other functions for creating new arrays. As examples, `zeros` and `ones` creates arrays of 0's or 1's, respectively with a given length or shape. `empty` creates an array without initializing its values to any particular value. To create a higher dimensional array with these methods, pass a tuple for the shape

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

`arange` is an array-valued version of the built-in Python `range` function.

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

|Function|Description|
|:--:|:--:|
|`array`|Convert input data to an ndarray either by inferring a dtype or explicitly specifying a `dtype`. Copies the input data by default|
|`asarray`|Convert input to ndarray, but do not copy if the inputs is already an ndarray|
|`arange`|Like the built-in `range` but returns an ndarray instead of a list|
|`ones`, `ones_like`|Produce an array of all 1's with the given shape and dtype. `ones_like` takes another array and produces a ones array of the same shape and dtype|
|`zeros`, `zeros_like`| Like `ones` and `ones_like` but producing arrays of 0's instead| 
|`empty`, `empty_like`| Create new arrays by allocating new memory, but do not populate with any values like `ones`and `zeros`|
|`eye`, `identity`| Create a square $N \times N$ identity matrix (1's on the diagonal and 0's elsewhere)|